// DO NOT EDIT MANUALLY. Generated by flutter_gherkin_parser.

import 'package:flutter_gherkin_parser/utils/integration_test_helper.dart';
import 'package:example/integration_test/test_config.dart';

import 'generated/subfolder/test_second_example_test_runner.dart' as test_second_example_test_runner;
import 'generated/test_test_runner.dart' as test_test_runner;
import 'generated/test_regex_driven_test_runner.dart' as test_regex_driven_test_runner;

void main() {
  IntegrationTestHelper(config: config);

  test_second_example_test_runner.main();
  test_test_runner.main();
  test_regex_driven_test_runner.main();
}
